---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: trino-configs-1
data:
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseGCOverheadLimit
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -Djava.rmi.server.hostname=trino-1
    -Dcom.sun.management.jmxremote.rmi.port=9081
  config.properties.coordinator: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=2GB
    # query.max-memory-per-node=1GB
    # query.max-total-memory-per-node=1GB
    query.max-stage-count=200
    task.writer-count=4
    # discovery-server.enabled=true
    discovery.uri=http://trino-1:8080
    jmx.rmiregistry.port=9080
    jmx.rmiserver.port=9081
    event-listener.config-files=/etc/trino/http-event-listener.properties
  http-event-listener.properties: |-
    event-listener.name=http
    http-event-listener.log-created=true
    http-event-listener.log-completed=true
    http-event-listener.connect-ingest-uri=http://10.0.2.15:5000/logs
  config.properties.worker: |-
    coordinator=false
    http-server.http.port=8080
    query.max-memory=2GB
    # query.max-memory-per-node=1GB
    # query.max-total-memory-per-node=1GB
    query.max-stage-count=200
    task.writer-count=4
    discovery.uri=http://trino-1:8080
    jmx.rmiregistry.port=9080
    jmx.rmiserver.port=9081
  node.properties: |-
    node.environment=test
    spiller-spill-path=/tmp
    max-spill-per-node=4TB
    query-max-spill-per-node=1TB
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mariadb:3306
    connection-user=tester
    connection-password=goodPass$123
